//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseHR.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpLeaveProfile
    {
        public string EmpId { get; set; }
        public decimal LTypeID { get; set; }
        public Nullable<decimal> LCarryOverd { get; set; }
        public Nullable<decimal> LEntitled { get; set; }
        public Nullable<decimal> LCashed { get; set; }
        public Nullable<decimal> LeaveEnjoyed { get; set; }
        public Nullable<decimal> LeaveElapsed { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string LastUpdatedFrom { get; set; }
        public Nullable<decimal> lvOpening { get; set; }
        public Nullable<decimal> lvPrevYearCarry { get; set; }
    
        public virtual EmpInfo EmpInfo { get; set; }
        public virtual LeaveTypeList LeaveTypeList { get; set; }
    }
}
