//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseHR.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpLeaveCTOEntitleLog
    {
        public decimal LogId { get; set; }
        public string EmpId { get; set; }
        public Nullable<decimal> LTypeId { get; set; }
        public Nullable<decimal> LEntitled { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Remarks { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> LYear { get; set; }
        public string EnjoyedStatus { get; set; }
        public Nullable<decimal> LvAppId { get; set; }
        public Nullable<decimal> LeaveEnjoyed { get; set; }
    
        public virtual LeaveTypeList LeaveTypeList { get; set; }
    }
}
