//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseHR.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeList
    {
        public decimal GradeId { get; set; }
        public string GradeName { get; set; }
        public string GradeDesc { get; set; }
        public string IsDeleted { get; set; }
        public string IsActive { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string LastUpdatedFrom { get; set; }
        public Nullable<decimal> BasicMin { get; set; }
        public Nullable<decimal> BasicMax { get; set; }
        public string GradeType { get; set; }
    }
}
