//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseHR.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeList
    {
        public OfficeList()
        {
            this.OfficeList1 = new HashSet<OfficeList>();
        }
    
        public decimal OfficeID { get; set; }
        public string OfficeTitle { get; set; }
        public Nullable<decimal> OfficeTypeID { get; set; }
        public Nullable<decimal> ParentID { get; set; }
        public string IsActive { get; set; }
        public string IsDeleted { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> DivID { get; set; }
        public Nullable<decimal> DistID { get; set; }
        public Nullable<decimal> UpzID { get; set; }
        public string IsPayLoc { get; set; }
    
        public virtual ICollection<OfficeList> OfficeList1 { get; set; }
        public virtual OfficeList OfficeList2 { get; set; }
    }
}
