//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseHR.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string USERID { get; set; }
        public string PASSWORD { get; set; }
        public string EmpId { get; set; }
        public string AccountDisabled { get; set; }
        public string ChangePassword { get; set; }
        public string IsRestricted { get; set; }
        public string IsAdmin { get; set; }
        public Nullable<int> PrivPackID { get; set; }
        public string IsDeleted { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string LastUpdatedFrom { get; set; }
    }
}
