//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseHR.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPriv
    {
        public decimal ID { get; set; }
        public string UserId { get; set; }
        public int ViewId { get; set; }
        public string ViewPerm { get; set; }
        public string InsertPerm { get; set; }
        public string DeletePerm { get; set; }
        public decimal InterventionId { get; set; }
        public decimal HeadOfficeId { get; set; }
        public decimal CCOId { get; set; }
        public Nullable<decimal> ZoneId { get; set; }
        public Nullable<decimal> UnitId { get; set; }
        public decimal AreaId { get; set; }
        public decimal BranchId { get; set; }
        public decimal DistrictId { get; set; }
        public decimal UpazillaId { get; set; }
        public decimal ProjectId { get; set; }
        public decimal GradeId { get; set; }
        public decimal SectorId { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string LastUpdatedFrom { get; set; }
    
        public virtual DivisionList DivisionList { get; set; }
        public virtual ViewName ViewName { get; set; }
    }
}
